pipeline:
  name: bdeploy
  identifier: bdeploy
  projectIdentifier: projectb
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: projectjj-deploy
        identifier: projectbdeploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: webbfrontend
          environment:
            environmentRef: webb
            deployToAll: false
            infrastructureDefinitions:
              - identifier: webbinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
